name: Auto-Pack

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller
          pip3 install -r requirements.txt

      - name: Pack to exe
        run: |
          mkdir szu_grab_course
          pyinstaller -F main.py
          mv dist/*.exe szu_grab_course/
          mv README.md szu_grab_course/
          mv setting.yaml szu_grab_course/
          mv des.min.js szu_grab_course/
          Compress-Archive -Path szu_grab_course -DestinationPath szu_grab_course.zip

      - name: Get commit info
        id: commit
        run: |
          echo "short=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT
          echo "title=$(git log -1 --pretty=%s)" >> $env:GITHUB_OUTPUT

      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: build
          path: szu_grab_course.zip

      - name: Create Pre-release And Upload Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: szu_grab_course.zip
          file_glob: true
          tag: ${{ steps.commit.outputs.short }}
          overwrite: true
          release_name: ${{ steps.commit.outputs.title }}
          body: |
            ${{ github.event.head_commit.message }}
          prerelease: true